import { ManagementType, PropertyStatus } from '@prisma/client';

export const mockProperty = (overrides: Record<string, any> = {}) => ({
  id: 'prop-1',
  organizationId: 'org-1',
  name: 'Test Property',
  managementType: ManagementType.WEG,
  propertyNumber: 'PROP-001',
  status: PropertyStatus.DRAFT,
  source: 'MANUAL',
  ownershipType: null,
  street: 'Musterstr.',
  houseNumber: '1',
  zipCode: '10115',
  city: 'Berlin',
  country: 'DE',
  managerId: 'manager-1',
  accountantId: null,
  sourceDocumentId: null,
  aiConfidenceScore: null,
  aiMeta: null,
  createdAt: new Date('2025-01-01'),
  updatedAt: new Date('2025-01-01'),
  createdById: null,
  updatedById: null,
  archivedAt: null,
  deletedAt: null,
  ...overrides,
});

export const mockBuilding = (overrides: Record<string, any> = {}) => ({
  id: 'bldg-1',
  propertyId: 'prop-1',
  label: 'Haus A',
  street: 'Musterstr.',
  houseNumber: '1',
  zipCode: '10115',
  city: 'Berlin',
  additionalInfo: null,
  docReference: null,
  externalId: null,
  createdAt: new Date('2025-01-01'),
  updatedAt: new Date('2025-01-01'),
  ...overrides,
});

export const mockUnit = (overrides: Record<string, any> = {}) => ({
  id: 'unit-1',
  propertyId: 'prop-1',
  buildingId: 'bldg-1',
  number: '1',
  type: 'APARTMENT',
  floor: 'EG',
  entrance: null,
  stairwell: null,
  sideOfBuilding: null,
  sizeSqm: 80,
  coOwnershipShare: 500,
  constructionYear: 2000,
  rooms: 3,
  isCommonProperty: false,
  usageNotes: null,
  docReference: null,
  externalId: null,
  isAiGenerated: false,
  isVerified: false,
  verificationMeta: null,
  createdAt: new Date('2025-01-01'),
  updatedAt: new Date('2025-01-01'),
  deletedAt: null,
  ...overrides,
});
